adminPanel/account/urls.py
from django.conf.urls import url
from .views import index, LoginView, ListHotels, LogoutView, CreateHotels, EditHotels

urlpatterns = [
    # give $ to end this url other wise, all the url will match with this
    # and you will not be able to see the expected response
    # url(r'^$', index, name='index'),
    url(r'^$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'hotels$', ListHotels.as_view(), name='list_hotels'),
    url(r'create_hotel/$', CreateHotels.as_view(), name='create_hotel'),
    url(r'edit_hotel/(?P<hotel_id>[0-9]+)/$', EditHotels.as_view(), name='update_hotel'),

]

adminPanel/adminPanel/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('account.urls', namespace='account'), name='account'),
    url(r'^inventory/', include('inventory.urls', namespace='inventory'), name='inventory'),
]

adminPanel/inventory/urls.py
from django.conf.urls import url
from views import ListInventory, EditProductView, DeleteProductView, CreateProductView, HotelDetailView, \
    CreatePredefinedProductView, EditPredefinedProductView, test, return_list, ListFormForInvoice, InvoiceClass, \
    get_file, AddInvoiceProduct, DeleteInvoiceProduct

urlpatterns = [
    # give $ to end this url other wise, all the url will match with this
    # and you will not be able to see the expected response
    url(r'^$', ListInventory.as_view(), name='list_inventory'),
    url(r'^edit/(?P<inventory_id>[0-9]+)/$', EditProductView.as_view(), name='update_product'),
    url(r'^delete/(?P<inventory_id>[0-9]+)/$', DeleteProductView.as_view(), name='delete_product'),
    url(r'^create/$', CreateProductView.as_view(), name='create_product'),

    # Hotel Details
    url(r'hotel_details/(?P<hotel_id>[0-9]+)/$', HotelDetailView.as_view(), name='hotel_details'),
    # create predefined product
    url(r'^create_predefined/(?P<hotel_id>[0-9]+)/$', CreatePredefinedProductView.as_view(), name='create_pre_product'),
    # update predefined product
    url(r'^update_predefined/(?P<hotel_id>[0-9]+)/(?P<predefined_id>[0-9]+)/$', EditPredefinedProductView.as_view(),
        name='update_pre_product'),
    # list invoice products
    url(r'^generate_invoice/(?P<hotel_id>[0-9]+)/(?P<invoice_date>[-0-9]+)$', ListFormForInvoice.as_view(), name='listform_for_invoice'),
    # get invoice list + update invoice products
    url(r'^invoice/(?P<hotel_id>[0-9]+)$', InvoiceClass.as_view(), name='invoice'),
    # add product to invoice
    url(r'^add_product_invoice/(?P<hotel_id>[0-9]+)/$', AddInvoiceProduct.as_view(), name='add_product_invoice'),
    # delete invoice products (allow everything in product_name regex using .+)
    url(r'^delete_product_invoice/(?P<hotel_id>[0-9]+)/(?P<invoice_date>[-0-9]+)/(?P<product_name>.+)/$',
        DeleteInvoiceProduct.as_view(), name='delete_product_invoice'),

    # Return the products based on query.
    url(r'return_list/$', return_list, name="return_list"),
    url(r'test$', test, name="test"),

    # download file request
    url(r'get_file/(?P<invoice_name>[a-zA-Z0-9-_ ]+)$', get_file, name="get_file"),

]

adminPanel/inventory/models.py
from __future__ import unicode_literals

from django.db import models
from account.models import HotelUser
from django.contrib.postgres.fields import JSONField


class BaseInventory(models.Model):
    inventory_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=100)
    quantity = models.FloatField(null=True)
    units = models.CharField(max_length=100, null=True)
    rate_per_unit = models.FloatField(null=True)
    amount = models.FloatField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']
        db_table = 'base_inventory'

    def __unicode__(self):
        return str(self.inventory_id)


class HotelPredefinedProducts(models.Model):
    predefined_id = models.AutoField(primary_key=True)
    hotel_id = models.ForeignKey(HotelUser, to_field='hotel_id', db_column='hotel_id', on_delete=models.CASCADE)
    # hotel_name = models.ForeignKey(HotelUser, to_field='hotel_name', db_column='hotel_name', related_name="hotel",
    #                                on_delete=models.CASCADE)
    hotel_name = models.CharField(max_length=500, db_column='hotel_name')
    product_id = models.ForeignKey(BaseInventory, to_field='inventory_id', db_column='product_id', on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100)
    quantity = models.FloatField(null=True)
    units = models.CharField(max_length=100, null=True)
    rate_per_unit = models.FloatField(null=True)
    amount = models.FloatField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return str(self.hotel_id)

    class Meta:
        db_table = 'hotel_predefined_products'
        ordering = ['updated_at']


class Invoice(models.Model):
    invoice_id = models.AutoField(primary_key=True)
    invoice_name = models.CharField(max_length=500, db_column='invoice_name')
    invoice_data = JSONField()
    pay_date = models.CharField(max_length=50, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return str(self.invoice_name)

    class Meta:
        db_table = 'invoice'
        ordering = ['updated_at']

adminPanel/inventory/forms.py
from django.forms import ModelForm
from models import BaseInventory


class BaseInventoryForm(ModelForm):

    class Meta:
        model = BaseInventory
        fields = ['product_name', 'quantity', 'rate_per_unit']

adminPanel/inventory/views.py
from django.shortcuts import render
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from models import BaseInventory, HotelPredefinedProducts, Invoice
from forms import BaseInventoryForm
from vanilla import CreateView, DeleteView, ListView, UpdateView, DetailView, View
from django.core.exceptions import ImproperlyConfigured
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, reverse
from account.models import HotelUser
import json
from collections import OrderedDict
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class ListInventory(ListView):
    """
    For listing base inventory.
    Class will use the model and find file with name model_list.html. It will list all the data from the model
    and add in the template and display.
    """
    model = BaseInventory

    def get_queryset(self):
        """
        Returns the base queryset for the view.

        Either used as a list of objects to display, or as the queryset
        from which to perform the individual object lookup.
        """
        if self.queryset is not None:
            return self.queryset._clone()

        if self.model is not None:
            return self.model._default_manager.all().order_by("product_name")

        msg = "'%s' must either define 'queryset' or 'model', or override 'get_queryset()'"
        raise ImproperlyConfigured(msg % self.__class__.__name__)


@method_decorator(login_required, name='dispatch')
class CreateProductView(CreateView):
    """
    This functionality is used for adding a new product to base inventory.
    This API is called from baseinventory_list.html --> create_form.html and redirects to baseinventory_list.html
    """
    lookup_field = 'inventory_id'
    model = BaseInventory
    form_class = BaseInventoryForm
    template_name = "inventory/create_form.html"

    def post(self, request, *args, **kwargs):
        amount = float(request.POST.get("quantity")) * float(request.POST.get("rate_per_unit"))

        BaseInventory.objects.create(product_name=request.POST.get("product_name"),
                                     quantity=request.POST.get("quantity"),
                                     units=request.POST.get("units"),
                                     rate_per_unit=request.POST.get("rate_per_unit"),
                                     amount=amount
                                     )
        return HttpResponseRedirect(reverse('inventory:list_inventory'))


@method_decorator(login_required, name='dispatch')
class EditProductView(UpdateView):
    """
    This functionality is used for updating the specific product of base inventory.
    This API is called from baseinventory_list.html --> update_form.html and redirects to baseinventory_list.html
    """
    lookup_field = 'inventory_id'
    model = BaseInventory

    def post(self, request, *args, **kwargs):
        inventory_id = kwargs["inventory_id"]
        amount = float(request.POST.get("quantity")) * float(request.POST.get("rate_per_unit"))

        update_product = BaseInventory.objects.get(inventory_id=inventory_id)
        update_product.product_name = request.POST.get("product_name")
        update_product.quantity = request.POST.get("quantity")
        update_product.units = request.POST.get("units")
        update_product.rate_per_unit = request.POST.get("rate_per_unit")
        update_product.amount = amount
        update_product.save()
        return HttpResponseRedirect(reverse('inventory:list_inventory'))


@method_decorator(login_required, name='dispatch')
class DeleteProductView(DeleteView):
    """
    This functionality is used for deleting the specific product of base inventory.
    This API is called from baseinventory_list.html --> update_form.html and redirects to baseinventory_list.html
    """
    lookup_field = 'inventory_id'
    model = BaseInventory

    def get(self, request, *args, **kwargs):
        inventory_id = kwargs["inventory_id"]
        BaseInventory.objects.get(inventory_id=inventory_id).delete()
        return HttpResponseRedirect(reverse('inventory:list_inventory'))


@method_decorator(login_required, name='dispatch')
class HotelDetailView(DetailView):
    """
    This functionality lists a particular hotel's predefined products. Page functionality has features for adding
    and editing predefined products, generating invoice and listing all invoices.
    API is called from hoteluser_list.html. (In account app)
    """
    lookup_field = 'hotel_id'

    def get(self, request, *args, **kwargs):
        hotel_id = kwargs["hotel_id"]
        try:
            hotel_name = HotelUser.objects.get(hotel_id=hotel_id).hotel_name
        except Exception, e:
            hotel_name = ""

        if hotel_name:
            products = HotelPredefinedProducts.objects.filter(hotel_id=hotel_id).order_by('product_name')
            res_list = list()
            for product in products:
                res = OrderedDict()
                res['predefined_id'] = product.predefined_id
                res['product_name'] = product.product_name
                res['quantity'] = product.quantity
                res['units'] = product.units
                res['rate_per_unit'] = product.rate_per_unit
                res['amount'] = product.amount

                res_list.append(res)

            return render(request, 'inventory/hotel_details.html', {"data": res_list, "hotel_name": hotel_name,
                                                                    "hotel_id": hotel_id})


@method_decorator(login_required, name='dispatch')
class CreatePredefinedProductView(CreateView):
    """
    This functionality includes Creating of predefined products from hotel's detail's page.
    API is called from hotel_details.html and redirects to hotel details page.
    """
    lookup_field = 'hotel_id'
    model = HotelPredefinedProducts
    # form_class = BaseInventoryForm
    # template_name = "inventory/create_form.html"

    def post(self, request, *args, **kwargs):
        hotel_id = kwargs["hotel_id"]
        hotel_id_instance = HotelUser.objects.get(hotel_id=hotel_id)
        hotel_name_instance = HotelUser.objects.get(hotel_name=hotel_id_instance.hotel_name)

        inventory_id = BaseInventory.objects.get(product_name=request.POST.get("product_name")).inventory_id
        inventory_id_instance = BaseInventory.objects.get(inventory_id=inventory_id)

        amount = float(request.POST.get("quantity")) * float(inventory_id_instance.rate_per_unit)

        HotelPredefinedProducts.objects.create(hotel_id=hotel_id_instance, hotel_name=hotel_name_instance,
                                               product_id=inventory_id_instance,
                                               product_name=request.POST.get("product_name"),
                                               quantity=request.POST.get("quantity"),
                                               units=request.POST.get("units"),
                                               rate_per_unit=float(inventory_id_instance.rate_per_unit),
                                               amount=amount,
                                               )
        return HttpResponseRedirect(reverse('inventory:hotel_details', kwargs={"hotel_id": hotel_id}))


@method_decorator(login_required, name='dispatch')
class EditPredefinedProductView(UpdateView):
    """
    This functionality includes updating of predefined products from hotel's detail's page.
    API is called from hotel_details.html and redirects to hotel details page.
    """
    lookup_field = 'hotel_id'
    model = HotelPredefinedProducts

    # form_class = BaseInventoryForm
    # template_name = "inventory/create_form.html"

    def post(self, request, *args, **kwargs):
        hotel_id = kwargs["hotel_id"]
        predefined_id = kwargs["predefined_id"]

        inventory_id = BaseInventory.objects.get(product_name=request.POST.get("product_name"))

        amount = float(request.POST.get("quantity")) * float(inventory_id.rate_per_unit)

        update_product = HotelPredefinedProducts.objects.get(hotel_id=hotel_id, predefined_id=predefined_id)
        update_product.product_name = request.POST.get("product_name")
        update_product.quantity = request.POST.get("quantity")
        update_product.units = request.POST.get("units")
        update_product.amount = amount

        update_product.save()

        return HttpResponseRedirect(reverse('inventory:hotel_details', kwargs={"hotel_id": hotel_id}))


@method_decorator(login_required, name='dispatch')
class ListFormForInvoice(ListView):
    """
    This functionality is used to display the invoice items. If the invoice is being created for the first time,
    then predefined products are shown else products from the edited invoice would be shown.
    API is called from hotel_details.html and renders generate_invoice.html
    """

    def get(self, request, *args, **kwargs):
        hotel_id = kwargs['hotel_id']
        print kwargs['invoice_date']
        try:
            hotel_name = HotelUser.objects.get(hotel_id=hotel_id).hotel_name
        except Exception, e:
            hotel_name = ""

        res_list = list()
        if hotel_name:
            invoice_name = hotel_name + "_" + kwargs['invoice_date']
            if Invoice.objects.filter(invoice_name=invoice_name).exists():
                products = Invoice.objects.filter(invoice_name=invoice_name)
                for product in products:
                    res_list = product.invoice_data
                return render(request, 'inventory/generate_invoice.html', {"data": res_list,
                                                                           "hotel_id": hotel_id, "has_invoice": 1})

            else:

adminPanel/templates/inventory/base_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base_dashboard.css' %}">
    <script type="text/javascript" src="{% static 'js/base_dashboard.js' %}"></script>
    <script src="{% static 'js/bootstrap-typeahead.js' %}"></script>


</head>

<body>
<!--New navbar-->
<div class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Rabbit</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="#">{{ user|title }}</a></li>
            {% endif %}
            <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
        </ul>
    </div>
</div>


<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-sm-3 col-md-2 sidebar" >
            <!--<br><br>-->
            <ul class="nav nav-sidebar" >
                <!--<li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>-->
                <li><a href="#">Dashboard</a></li>
                <li><a href="{% url 'inventory:list_inventory' %}">Inventory</a></li>
                <li><a href="{% url 'account:list_hotels' %}">Know Your Business</a></li>
                <li><a href="#">Payment</a></li>
            </ul>
        </div>

        <!--Enter block content here -->

        {% block content %}
        {% endblock %}

        <!--<footer>-->
        <!--<p>© Smerkato 2017</p>-->
        <!--</footer>-->

    </div>
</div>
</body>
</html>

adminPanel/templates/inventory/baseinventory_list.html
{% extends 'inventory/base_dashboard.html' %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-0 main">
    <h1 class="page-header">BaseInventory</h1>
    <!--<h1 style="margin: 30px;">Dashboard</h1>-->
    <!--<div style="margin: 30px">-->

    <div class="container-fluid">
        {% include "inventory/create_form.html" %}
    </div>
    <br>
    <div>
        {% if baseinventory_list %}
        <table class="table table-striped">
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Units</th>
                <th>Rate/Unit</th>
                <th>Amount</th>
                <th></th>
                <th></th>
            </tr>
            {% for base in baseinventory_list %}
            <tr>
                <td>{{ base.product_name }}</td>
                <td>{{ base.quantity }}</td>
                <td>{{ base.units }}</td>
                <td>{{ base.rate_per_unit }}</td>
                <td>{{ base.amount }}</td>
                <!--<td><a href="{% url 'inventory:update_product' base.inventory_id %}">Edit</a> </td>-->
                <td>{% include "inventory/update_form.html" with base_id=base.inventory_id %}</td>
                <td>
                    <form method="GET" action="{% url 'inventory:delete_product' base.inventory_id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" data-toggle="modal"
                                data-original-title="Delete product">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

adminPanel/templates/inventory/create_form.html
<!-- Trigger the modal with a button -->

<button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal"
        data-original-title="Add new product"><span class="glyphicon glyphicon-plus"></span></button>

<!--Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add New Product</h4>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'inventory:create_product' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="product_namee">Product Name:</label>
                        <br>
                        <input required type="text" class="form-control" id="product_namee"
                               placeholder="Enter Product Name" name="product_name">
                    </div>
                    <div class="form-group">
                        <label for="quantity">Quantity:</label>
                        <input required type="number" step="0.01" class="form-control" id="quantity" placeholder="Enter Quantity"
                               name="quantity">
                    </div>
                    <div class="form-group">
                        <label for="units">Units:</label>
                        <select class="form-control" id="units" name="units">
                            <option>KGs</option>
                            <option>Grams</option>
                            <option>Ml</option>
                            <option>Ltrs</option>
                            <option>Bags</option>
                            <option>Tins</option>
                            <option>Pouches</option>
                            <option>Boxes</option>
                            <option>Pieces</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="rate_per_unit">Rate Per Unit:</label>
                        <input required type="number" step="0.01" class="form-control" id="rate_per_unit" placeholder="Enter Rate Per Unit"
                               name="rate_per_unit">
                    </div>
                    <button type="submit" class="btn btn-danger">Submit</button>
                </form>
            </div>
        </div>

    </div>
</div>

adminPanel/templates/inventory/generate_invoice.html
{% extends 'inventory/base_dashboard.html' %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-0 main">
    {% now "d-m-Y" as current_date %}

    <!--<h2 class="page-header">Invoice for Date: <span id="date"></span></h2>-->
    <h2 class="page-header">Invoice for Date: {{ current_date }}</h2>
    <!--<h1 style="margin: 30px;">Dashboard</h1>-->
    <!--<div style="margin: 30px">-->
    {% include "inventory/add_product_to_invoice.html" %}
    <br>
    <div>
        {% if data %}
        <form method="POST" action="{% url 'inventory:invoice' hotel_id %}">
            {% csrf_token %}
            <table class="table table-hover table-responsive">
                <tr>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Units</th>
                    <th>Rate/Unit</th>
                </tr>

                {% for dt in data %}
                <tr>
                    <td>
                        <div class="form-group"><input required type="text" class="form-control"
                                                       id="p_name-{{ forloop.counter }}" value="{{ dt.product_name }}"
                                                       name="p_name-{{ forloop.counter }}" readonly></div>
                    </td>
                    <td>
                        <div class="form-group"><input required type="number" step="0.01" class="form-control"
                                                       id="quantity-{{ forloop.counter }}" value="{{ dt.quantity }}"
                                                       name="quantity-{{ forloop.counter }}"></div>
                    </td>
                    <td>
                        <div class="form-group"><input required type="text" class="form-control"
                                                       id="units-{{ forloop.counter }}" value="{{ dt.units }}"
                                                       name="units-{{ forloop.counter }}" readonly></div>
                    </td>
                    <td>
                        <div class="form-group"><input required type="number" step="0.01" class="form-control"
                                                       id="rate_per_unit-{{ forloop.counter }}" value="{{ dt.rate_per_unit }}"
                                                       name="rate_per_unit-{{ forloop.counter }}"></div>
                    </td>
                    <td>
                        <form method="POST" action="{% url 'inventory:delete_product_invoice' hotel_id current_date dt.product_name %}">
                        {% csrf_token %}
                            <button type="submit" class="btn btn-danger" data-toggle="modal"
                                data-original-title="Delete Product from current Invoice">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <div class="checkbox form-group">
              <label><input type="checkbox" value="" id="save_checkbox" name="save_checkbox">Save to Orders</label>
            </div>
            <div class="form-group">
                <label id="pay_label">Enter Pay Date:  <input type="text" value="" id="pay_date"
                                                              name="pay_date" placeholder=" DD-MM-YYYY"></label>
            </div>
            <div class="form-group">
                <input type="hidden" value="{{ current_date }}" id="invoice_date" name="invoice_date">
            </div>
            <button id="submit_invoice" type="submit" class="btn btn-info">Save Invoice</button>

        </form>
        {% endif %}
    </div>
</div>

<script>
$(document).ready(function(){
    <!--var d = new Date();-->
    <!--var strDate = d.getDate() + "-" + (d.getMonth()+1) + "-" + d.getFullYear();-->
    <!--$('#date').html(strDate);-->
    <!--$('#invoice_date').val(strDate);-->
    $('#pay_label').hide();
    $('#pay_date').prop('required', false);
    $('#save_checkbox').on('click', function(){
        $('#pay_label').toggle();
        if ($('#pay_date').prop('required')){
            $('#pay_date').prop('required', false);
            $('#submit_invoice').html("Save Invoice");
        }
        else {
            $('#pay_date').prop('required', true);
            $('#submit_invoice').html("Save Invoice and Download");
        }
    });

});

</script>

{% endblock %}

adminPanel/templates/inventory/hotel_details.html
{% extends 'inventory/base_dashboard.html' %}
{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-0 main">
    {% now "d-m-Y" as current_date %}
    <!--<a href="{% url 'inventory:listform_for_invoice' hotel_id current_date %}" class="btn btn-default" data-toggle="modal"-->
            <!--data-original-title="Generate Invoice" id="check">-->
    <!--</a>-->


    <h1 class="page-header">{{ hotel_name }} Products</h1>
    <!--<h1 style="margin: 30px;">Dashboard</h1>-->
    <!--<div style="margin: 30px">-->

    <div class="container-fluid">
        <div class="row">
            <div class="well col-md-3 col-md-offset-0" style="width:100px;height:100px;">
            {% include "inventory/create_predefined_products.html" %}
            </div>
            <div class="well col-md-3 col-md-offset-1" style="width:100px;height:100px;">
                <a href="{% url 'inventory:listform_for_invoice' hotel_id current_date %}" class="btn btn-info"
                   data-toggle="modal" data-original-title="Generate Invoice">
                    <span class="glyphicon glyphicon-plus"></span></a>
            </div>
            <div class="well col-md-3 col-md-offset-1" style="width:100px;height:100px;">
                <a href="{% url 'inventory:invoice' hotel_id %}" class="btn btn-info" data-toggle="modal"
                data-original-title="View Invoices"><span class="glyphicon glyphicon-plus"></span></a>
            </div>
        </div>
    </div>
    <br>
    <div>
        {% if data %}
        <table class="table table-striped">
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Units</th>
                <th>Rate/Unit</th>
                <th>Amount</th>
                <th></th>
                <th></th>
            </tr>
            {% for dt in data %}
            <tr>
                <td>{{ dt.product_name }}</td>
                <td>{{ dt.quantity }}</td>
                <td>{{ dt.units }}</td>
                <td>{{ dt.rate_per_unit }}</td>
                <td>{{ dt.amount }}</td>
                <td>{% include "inventory/update_predefined_products.html" %}</td>
                <td>
                    <form method="GET" action="#">
                    <!--{% csrf_token %}-->
                        <button type="submit" class="btn btn-danger" data-toggle="modal"
                        data-original-title="Delete Product">
                        <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>

<style>
    background-image: "/home/divya/workspace/latest/rabbit-project/adminPanel/templates/inventory/smerkato.png"
</style>
{% endblock %}

adminPanel/templates/inventory/invoice_list.html
{% extends 'inventory/base_dashboard.html' %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-0 main">
    {% now "d-m-Y" as current_date %}

    <!--<h2 class="page-header">Invoice for Date: <span id="date"></span></h2>-->
    <h2 class="page-header">Invoices :  {{ hotel_name|title }}</h2>
    <!--<h1 style="margin: 30px;">Dashboard</h1>-->
    <!--<div style="margin: 30px">-->
    <br>
    <div>
        {% if data %}
            <table class="table table-hover table-responsive">
                <tr>
                    <th>S. No.</th>
                    <th>Invoices</th>
                    <th>Last Modified</th>
                </tr>
                {% for dt in data %}
                <tr>
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        <a href="{% url 'inventory:get_file' dt.invoice_name %}">{{ dt.invoice_name }}</a>
                    </td>
                    <td>
                        {{ dt.last_modified }}
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>

</div>
{% endblock %}

adminPanel/templates/inventory/payment.html
{% extends 'inventory/base_dashboard.html' %}

{% block content %}

<p><mark>Coming Soon</mark></p>

{% endblock %}